// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/protocol.proto

package io.github.notoday.netty.remoting.protocol.protobuf;

/**
 * Protobuf type {@code RemotingCommandProtobuf}
 */
public final class RemotingCommandProtobuf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RemotingCommandProtobuf)
    RemotingCommandProtobufOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemotingCommandProtobuf.newBuilder() to construct.
  private RemotingCommandProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemotingCommandProtobuf() {
    remark_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemotingCommandProtobuf();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.notoday.netty.remoting.protocol.protobuf.Protocol.internal_static_RemotingCommandProtobuf_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 7:
        return internalGetExtFields();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.notoday.netty.remoting.protocol.protobuf.Protocol.internal_static_RemotingCommandProtobuf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.class, io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_ = 0;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int REQID_FIELD_NUMBER = 2;
  private int reqId_ = 0;
  /**
   * <code>int32 reqId = 2;</code>
   * @return The reqId.
   */
  @java.lang.Override
  public int getReqId() {
    return reqId_;
  }

  public static final int FLAG_FIELD_NUMBER = 3;
  private int flag_ = 0;
  /**
   * <code>int32 flag = 3;</code>
   * @return The flag.
   */
  @java.lang.Override
  public int getFlag() {
    return flag_;
  }

  public static final int CODE_FIELD_NUMBER = 4;
  private int code_ = 0;
  /**
   * <code>int32 code = 4;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int REMARK_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object remark_ = "";
  /**
   * <code>optional string remark = 5;</code>
   * @return Whether the remark field is set.
   */
  @java.lang.Override
  public boolean hasRemark() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string remark = 5;</code>
   * @return The remark.
   */
  @java.lang.Override
  public java.lang.String getRemark() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      remark_ = s;
      return s;
    }
  }
  /**
   * <code>optional string remark = 5;</code>
   * @return The bytes for remark.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRemarkBytes() {
    java.lang.Object ref = remark_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      remark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 6;
  private com.google.protobuf.Any body_;
  /**
   * <code>optional .google.protobuf.Any body = 6;</code>
   * @return Whether the body field is set.
   */
  @java.lang.Override
  public boolean hasBody() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .google.protobuf.Any body = 6;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.google.protobuf.Any getBody() {
    return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
  }
  /**
   * <code>optional .google.protobuf.Any body = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
    return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
  }

  public static final int EXTFIELDS_FIELD_NUMBER = 7;
  private static final class ExtFieldsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.github.notoday.netty.remoting.protocol.protobuf.Protocol.internal_static_RemotingCommandProtobuf_ExtFieldsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> extFields_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExtFields() {
    if (extFields_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtFieldsDefaultEntryHolder.defaultEntry);
    }
    return extFields_;
  }
  public int getExtFieldsCount() {
    return internalGetExtFields().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; extFields = 7;</code>
   */
  @java.lang.Override
  public boolean containsExtFields(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetExtFields().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtFieldsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExtFields() {
    return getExtFieldsMap();
  }
  /**
   * <code>map&lt;string, string&gt; extFields = 7;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getExtFieldsMap() {
    return internalGetExtFields().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; extFields = 7;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getExtFieldsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtFields().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; extFields = 7;</code>
   */
  @java.lang.Override
  public java.lang.String getExtFieldsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtFields().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (reqId_ != 0) {
      output.writeInt32(2, reqId_);
    }
    if (flag_ != 0) {
      output.writeInt32(3, flag_);
    }
    if (code_ != 0) {
      output.writeInt32(4, code_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, remark_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getBody());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetExtFields(),
        ExtFieldsDefaultEntryHolder.defaultEntry,
        7);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    if (reqId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, reqId_);
    }
    if (flag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, flag_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, code_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, remark_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getBody());
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExtFields().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      extFields__ = ExtFieldsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, extFields__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf)) {
      return super.equals(obj);
    }
    io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf other = (io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (getReqId()
        != other.getReqId()) return false;
    if (getFlag()
        != other.getFlag()) return false;
    if (getCode()
        != other.getCode()) return false;
    if (hasRemark() != other.hasRemark()) return false;
    if (hasRemark()) {
      if (!getRemark()
          .equals(other.getRemark())) return false;
    }
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (!internalGetExtFields().equals(
        other.internalGetExtFields())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId();
    hash = (37 * hash) + FLAG_FIELD_NUMBER;
    hash = (53 * hash) + getFlag();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    if (hasRemark()) {
      hash = (37 * hash) + REMARK_FIELD_NUMBER;
      hash = (53 * hash) + getRemark().hashCode();
    }
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    if (!internalGetExtFields().getMap().isEmpty()) {
      hash = (37 * hash) + EXTFIELDS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtFields().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RemotingCommandProtobuf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RemotingCommandProtobuf)
      io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobufOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.notoday.netty.remoting.protocol.protobuf.Protocol.internal_static_RemotingCommandProtobuf_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetExtFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableExtFields();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.notoday.netty.remoting.protocol.protobuf.Protocol.internal_static_RemotingCommandProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.class, io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.Builder.class);
    }

    // Construct using io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBodyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = 0;
      reqId_ = 0;
      flag_ = 0;
      code_ = 0;
      remark_ = "";
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      internalGetMutableExtFields().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.notoday.netty.remoting.protocol.protobuf.Protocol.internal_static_RemotingCommandProtobuf_descriptor;
    }

    @java.lang.Override
    public io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf getDefaultInstanceForType() {
      return io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf build() {
      io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf buildPartial() {
      io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf result = new io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reqId_ = reqId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.flag_ = flag_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.code_ = code_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.remark_ = remark_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.body_ = bodyBuilder_ == null
            ? body_
            : bodyBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.extFields_ = internalGetExtFields();
        result.extFields_.makeImmutable();
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf) {
        return mergeFrom((io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf other) {
      if (other == io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getReqId() != 0) {
        setReqId(other.getReqId());
      }
      if (other.getFlag() != 0) {
        setFlag(other.getFlag());
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (other.hasRemark()) {
        remark_ = other.remark_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      internalGetMutableExtFields().mergeFrom(
          other.internalGetExtFields());
      bitField0_ |= 0x00000040;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              version_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              reqId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              flag_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              code_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              remark_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extFields__ = input.readMessage(
                  ExtFieldsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableExtFields().getMutableMap().put(
                  extFields__.getKey(), extFields__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      onChanged();
      return this;
    }

    private int reqId_ ;
    /**
     * <code>int32 reqId = 2;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public int getReqId() {
      return reqId_;
    }
    /**
     * <code>int32 reqId = 2;</code>
     * @param value The reqId to set.
     * @return This builder for chaining.
     */
    public Builder setReqId(int value) {
      
      reqId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reqId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReqId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      reqId_ = 0;
      onChanged();
      return this;
    }

    private int flag_ ;
    /**
     * <code>int32 flag = 3;</code>
     * @return The flag.
     */
    @java.lang.Override
    public int getFlag() {
      return flag_;
    }
    /**
     * <code>int32 flag = 3;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(int value) {
      
      flag_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 flag = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {
      bitField0_ = (bitField0_ & ~0x00000004);
      flag_ = 0;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 code = 4;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 4;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      
      code_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000008);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object remark_ = "";
    /**
     * <code>optional string remark = 5;</code>
     * @return Whether the remark field is set.
     */
    public boolean hasRemark() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string remark = 5;</code>
     * @return The remark.
     */
    public java.lang.String getRemark() {
      java.lang.Object ref = remark_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        remark_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string remark = 5;</code>
     * @return The bytes for remark.
     */
    public com.google.protobuf.ByteString
        getRemarkBytes() {
      java.lang.Object ref = remark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string remark = 5;</code>
     * @param value The remark to set.
     * @return This builder for chaining.
     */
    public Builder setRemark(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      remark_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string remark = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemark() {
      remark_ = getDefaultInstance().getRemark();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string remark = 5;</code>
     * @param value The bytes for remark to set.
     * @return This builder for chaining.
     */
    public Builder setRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      remark_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any body_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     * @return The body.
     */
    public com.google.protobuf.Any getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    public Builder setBody(com.google.protobuf.Any value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
      } else {
        bodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    public Builder setBody(
        com.google.protobuf.Any.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    public Builder mergeBody(com.google.protobuf.Any value) {
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          body_ != null &&
          body_ != com.google.protobuf.Any.getDefaultInstance()) {
          getBodyBuilder().mergeFrom(value);
        } else {
          body_ = value;
        }
      } else {
        bodyBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    public Builder clearBody() {
      bitField0_ = (bitField0_ & ~0x00000020);
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    public com.google.protobuf.Any.Builder getBodyBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : body_;
      }
    }
    /**
     * <code>optional .google.protobuf.Any body = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extFields_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetExtFields() {
      if (extFields_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtFieldsDefaultEntryHolder.defaultEntry);
      }
      return extFields_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableExtFields() {
      if (extFields_ == null) {
        extFields_ = com.google.protobuf.MapField.newMapField(
            ExtFieldsDefaultEntryHolder.defaultEntry);
      }
      if (!extFields_.isMutable()) {
        extFields_ = extFields_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return extFields_;
    }
    public int getExtFieldsCount() {
      return internalGetExtFields().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    @java.lang.Override
    public boolean containsExtFields(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExtFields().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtFieldsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtFields() {
      return getExtFieldsMap();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getExtFieldsMap() {
      return internalGetExtFields().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getExtFieldsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtFields().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    @java.lang.Override
    public java.lang.String getExtFieldsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtFields().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearExtFields() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableExtFields().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    public Builder removeExtFields(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableExtFields().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableExtFields() {
      bitField0_ |= 0x00000040;
      return internalGetMutableExtFields().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    public Builder putExtFields(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableExtFields().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; extFields = 7;</code>
     */
    public Builder putAllExtFields(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExtFields().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RemotingCommandProtobuf)
  }

  // @@protoc_insertion_point(class_scope:RemotingCommandProtobuf)
  private static final io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf();
  }

  public static io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemotingCommandProtobuf>
      PARSER = new com.google.protobuf.AbstractParser<RemotingCommandProtobuf>() {
    @java.lang.Override
    public RemotingCommandProtobuf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RemotingCommandProtobuf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemotingCommandProtobuf> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.notoday.netty.remoting.protocol.protobuf.RemotingCommandProtobuf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

